# Generated by Django 4.2 on 2025-07-18 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_limit',
            field=models.IntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
