# Generated by Django 4.2 on 2025-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0002_alter_attendance_time_limit_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
