# Generated by Django 4.2 on 2025-07-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0002_alter_student_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
    ]
