# Generated by Django 4.2 on 2025-08-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0003_attendance_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date', 'time_limit')},
        ),
    ]
